version: '3.4'

services:
  mongo:
    image: mongo:4.0.4
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./create-app-user.sh:/docker-entrypoint-initdb.d/create-app-user.sh
      - mongodata:/data/db
    networks:
      - mongo-compose-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo admin -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
      retries: 3
    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--oplogSize", "50", "--bind_ip_all"] 

networks: 
  mongo-compose-network:
    driver: bridge

volumes:
  mongodata:


